#!/bin/sh

RED="\033[1;31m";
GREEN="\033[1;32m";

FILES=$(git diff --cached --diff-filter=d --name-only | grep  -E '\.(?:t|j)sx?$');

# skip if there are no files
[ -z "$FILES" ] && exit 0;

# run type-check
./node_modules/.bin/tsc --pretty --noEmit

# save exit code
tsc_exit_code=$?;

# check the tsc exit code
if [ $tsc_exit_code -ne 0 ]; then
    echo "${RED} ❌ Error with Type-checking. 😑";
    exit 1;
fi

echo "${GREEN} 👍 Good coder. No errors found 😁";
exit 0;
