#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACM);
[ -z "$FILES" ] && exit 0;

# save staged/unstaged files
echo "$FILES" > ".github/hooks/S.log" &
echo "$(git diff --name-only --diff-filter=ACM)" > ".github/hooks/U.log";

# get fully-staged file names
FULLY_STAGED=$(comm -23 ".github/hooks/S.log" ".github/hooks/U.log");

rm -f ".github/hooks/S.log" ".github/hooks/U.log" &
npx git-format-staged -f "prettier --stdin-filepath '{}'" "*.js" "*.ts" "*.tsx" "*.json" &
echo "$FILES" | grep -E "\.(?:t|j)sx?$" | xargs npx eslint --quiet --fix --cache;

linter_exit_code=$?;

# check the linter exit code
if [ $linter_exit_code -ne 0 ]; then
  exit 1;
fi

# add back the modified/prettified files to staging
git add "$FULLY_STAGED";

exit 0;
