#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR);
[ -z "$FILES" ] && exit 0;

# run type-check
./node_modules/.bin/tsc --pretty --noEmit;
tsc_exit_code=$?;

# check the tsc exit code
if [ $tsc_exit_code -ne 0 ]; then
  echo "❌ Typescript errors";
  exit 1;
fi

echo "👍";
exit 0;
