#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR);
[ -z "$FILES" ] && exit 0;

# run type-check
npx tsc --pretty --noEmit && npm run build;
tsc_exit_code=$?;

# check the tsc exit code
if [ $tsc_exit_code -ne 0 ]; then
  exit 1;
fi

exit 0;
